# Generated by Django 3.0.7 on 2020-07-06 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('verified', 'verified'), ('inProcess', 'inProcess'), ('sold', 'sold')], default='pending', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelNumber', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('old', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='L', max_length=10)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=10)),
                ('status', models.CharField(choices=[('inStock', 'inStock'), ('inProcess', 'inProcess'), ('sold', 'sold')], default='inStock', max_length=10)),
                ('old', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('fullName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=20)),
                ('confirmPassword', models.CharField(max_length=20)),
                ('contactNumber', models.CharField(max_length=12)),
                ('year', models.CharField(choices=[('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY'), ('LY', 'LY')], default='FY', max_length=2)),
                ('branch', models.CharField(choices=[('IT', 'IT'), ('COMPS', 'COMPS'), ('EXTC', 'EXTC'), ('ETRX', 'ETRX'), ('MECH', 'MECH')], default='IT', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
                ('year', models.CharField(choices=[('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY'), ('LY', 'LY')], default='FY', max_length=2)),
                ('branch', models.CharField(choices=[('IT', 'IT'), ('COMPS', 'COMPS'), ('EXTC', 'EXTC'), ('ETRX', 'ETRX'), ('MECH', 'MECH')], default='IT', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('fullName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=20)),
                ('confirmPassword', models.CharField(max_length=20)),
                ('contactNumber', models.CharField(max_length=12)),
                ('year', models.CharField(choices=[('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY'), ('LY', 'LY')], default='FY', max_length=2)),
                ('branch', models.CharField(choices=[('IT', 'IT'), ('COMPS', 'COMPS'), ('EXTC', 'EXTC'), ('ETRX', 'ETRX'), ('MECH', 'MECH')], default='IT', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Report_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_books', to='ccapp.Book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_books', to='ccapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Coat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('coat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_coats', to='ccapp.Coat')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_coats', to='ccapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Calculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('calculator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_calculators', to='ccapp.Calculator')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_calculators', to='ccapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_books', to='ccapp.Book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_books', to='ccapp.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='coat',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coats', to='ccapp.Seller'),
        ),
        migrations.AddField(
            model_name='calculator',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculators', to='ccapp.Seller'),
        ),
        migrations.AddField(
            model_name='book',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='ccapp.Seller'),
        ),
    ]
