# Generated by Django 3.0.7 on 2021-01-11 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0002_deletedemails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculator',
            name='modelNumber',
        ),
        migrations.RemoveField(
            model_name='coat',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='coat',
            name='status',
        ),
        migrations.CreateModel(
            name='Suit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='L', max_length=10)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=10)),
                ('old', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suits', to='ccapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Toolkit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_toolkits', to='ccapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Suit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_suits', to='ccapp.Student')),
                ('suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_suits', to='ccapp.Suit')),
            ],
        ),
    ]
