# Generated by Django 3.0.7 on 2021-01-13 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0003_auto_20210111_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculator',
            name='price',
        ),
        migrations.RemoveField(
            model_name='coat',
            name='price',
        ),
        migrations.RemoveField(
            model_name='suit',
            name='price',
        ),
    ]
