# Generated by Django 3.0.7 on 2021-01-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0004_auto_20210113_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coat',
            name='old',
        ),
        migrations.RemoveField(
            model_name='suit',
            name='old',
        ),
        migrations.AddField(
            model_name='coat',
            name='condition',
            field=models.CharField(choices=[('used', 'used'), ('new', 'new')], default='used', max_length=4),
        ),
        migrations.AddField(
            model_name='suit',
            name='condition',
            field=models.CharField(choices=[('used', 'used'), ('new', 'new')], default='used', max_length=4),
        ),
        migrations.AddField(
            model_name='suit',
            name='status',
            field=models.CharField(choices=[('inStock', 'inStock'), ('inProcess', 'inProcess'), ('sold', 'sold')], default='inStock', max_length=10),
        ),
    ]
