# Generated by Django 3.0.7 on 2021-01-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0005_auto_20210113_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='status',
            field=models.CharField(choices=[('inStock', 'inStock'), ('inProcess', 'inProcess'), ('sold', 'sold')], default='inStock', max_length=10),
        ),
    ]
