# Generated by Django 3.0.7 on 2021-01-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0007_auto_20210113_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='coat',
            name='status',
            field=models.CharField(choices=[('inStock', 'inStock'), ('inProcess', 'inProcess'), ('sold', 'sold')], default='inStock', max_length=10),
        ),
        migrations.AlterField(
            model_name='coat',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='L', max_length=10),
        ),
        migrations.AlterField(
            model_name='suit',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='L', max_length=10),
        ),
    ]
