# Generated by Django 3.0.7 on 2021-01-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0008_auto_20210113_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculator',
            name='old',
        ),
        migrations.AddField(
            model_name='calculator',
            name='condition',
            field=models.CharField(choices=[('used', 'used'), ('new', 'new')], default='used', max_length=4),
        ),
    ]
