# Generated by Django 3.0.7 on 2021-01-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0009_auto_20210113_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
